### ISSUE TITLE
Doesn't work in IE on Windows Surface and on iOS

### ISSUE THREAD

**Issue by ArtbyArjan** [FaroeMedia/scrollator#4]
For a website I'm building, I'm looking into a (jQuery) plugin with which I can change the appearance of the scrollbar, and a search through Google brought me here.
By testing your demo webpage on several devices, I found out that it doesn't work on the following:

- Chrome and Safari on iPad 1 with iOS 5.1.1
- Chrome and Safari on iPad 4 with iOS 8.1.2
- IE11 on Windows Surface with Windows RT 8.1
- IE on HTC Windows Phone with Windows Phone 8X

**Comment by ingipingi** [comment]
The plugin was initially made for desktop browsers, to replace current scrollbars because of the space current scrollbars take, we wanted a spaceless overlaying scrollbar.
And since most handheld devices already have spaceless scrollbars, it was not needed on handheld devices.
It automatically disables itself on handheld devices.
You can disable lines 238 and 295 to test on handheld devices. 238 is the line with the check for handheld devices (if ( !/Android|webOS|iPhone|...)

**Comment by ArtbyArjan** [comment]
You meant line 283 and 295 I assume?
I tried that, but that only makes it worse :)

With both lines enabled, you can still scroll in the elements on your demopage, but with both lines disabled, the scrollbar shows up for a brief moment, and then disappears, but you can't scroll inside the elements.
Too bad about that.

I take it you're not planning to improve the plugin so it does work on mobile devices?

**Comment by ingipingi** [comment]
Not at this point, because mobile browsers introduce a whole myriad of problems when trying to make a scroll-bar.
Here is a list of different plugins with demo pages you could test: http://www.jqueryrain.com/2012/07/jquery-scrollbar-plugin-examples/
